/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Cliente;
import beans.Itens;
import beans.Produto;
import beans.Venda;
import dao.VendaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael
 */
public class FormVendas extends javax.swing.JFrame {
    
    public void recebeCliente(Cliente c) {
        txtIdCliente.setText(String.valueOf(c.getId()));
        txtNomeCliente.setText(c.getNomecliente());
    }
    
    //recebe o Produto e a qtde lá do FormPesquisarProduto e insere na tblItens
    public void recebeProduto(Produto p, int quantidade) {
        int numeroLinha = verificarItemDuplicado(p.getId());
        if(numeroLinha == -1) {
            //Produto novo, add uma nova linha
            DefaultTableModel tabela = (DefaultTableModel) tblItens.getModel();
            Object[] novaLinha = new Object[]{
                p.getId(),
                p.getNomeproduto(),
                p.getValor(),
                quantidade,
                p.getValor() * quantidade
            };
            tabela.addRow(novaLinha);
        }
        else {
            //Já tem o produto na tabela, então só altera a quantidade
            int qtdeAtual = Integer.parseInt(tblItens.getValueAt(numeroLinha, 3).toString());
            int novaQtde = qtdeAtual + quantidade;
            double novoTotal = novaQtde * p.getValor();
            
            tblItens.setValueAt(novaQtde, numeroLinha, 3);
            tblItens.setValueAt(novoTotal, numeroLinha, 4);
        }
        calcularValorTotal();
    }
    
    //retorna a qtde atual do item na tblItens (para ser usado no calculo do estoque)
    public int getQuantidadeItem(int id) {
        int quantidade = 0;
        for(int i = 0; i < tblItens.getRowCount(); i++) {
            int idAtual = Integer.parseInt(tblItens.getValueAt(i, 0).toString());
            if(idAtual == id) {
                //encontrou o produto, pegue a quantidade dele
                quantidade = Integer.parseInt(tblItens.getValueAt(i, 3).toString());
                break;
            }
        }
        return quantidade;
    }
    
    //retorna o número da linha do produto duplicado
    //ou -1 se ainda nao existe na tabela
    private int verificarItemDuplicado(int id) {
        int numeroLinha = -1;
        for(int i = 0; i < tblItens.getRowCount(); i++) {
            //verifica se o id da linha atual (i) é igual ao id que veio como param.
            int idAtual = Integer.parseInt(tblItens.getValueAt(i, 0).toString());
            if(idAtual == id){
                numeroLinha = i;
                break; //interrompe o laço, pq já encontrou o que estava procurando
            }
        }
        return numeroLinha;
    }
    
    private void calcularValorTotal() {
        double valorTotal = 0;
        //percorre a tblItens e vai somando todos os "totais"
        for(int i = 0; i < tblItens.getRowCount(); i++) {
            double totalItem = Double.parseDouble(tblItens.getValueAt(i, 4).toString());
            valorTotal += totalItem;
        }
        txtValorTotal.setText(String.valueOf(valorTotal));
    }

    /**
     * Creates new form FormVendas
     */
    public FormVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnAdicionarItem = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cmbFormaPagamento = new javax.swing.JComboBox<>();
        btnConcluirVenda = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Vendas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Formulário de Vendas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel2.setText("Cliente:");

        txtIdCliente.setEditable(false);
        txtIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N

        btnPesquisarCliente.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel3.setText("Data Venda:");

        txtDataVenda.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Produto", "Nome do Produto", "Valor", "Quantidade", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblItens);

        btnAdicionarItem.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnAdicionarItem.setText("+ Item");
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnRemoverItem.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel4.setText("Forma de Pagamento:");

        cmbFormaPagamento.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        cmbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão Débito", "Cartão Crédito", "PIX" }));

        btnConcluirVenda.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnConcluirVenda.setText("Concluir Venda");
        btnConcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirVendaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 23)); // NOI18N
        jLabel5.setText("Total:");

        txtValorTotal.setEditable(false);
        txtValorTotal.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 23)); // NOI18N
        txtValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotal.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAdicionarItem))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(246, 246, 246)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnPesquisarCliente))
                                        .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConcluirVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRemoverItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverItem)
                    .addComponent(jLabel5)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnConcluirVenda)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        // TODO add your handling code here:
        FormPesquisarCliente fpc = new FormPesquisarCliente(this, true);
        fpc.setFv(this);
        fpc.setVisible(true);
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        // TODO add your handling code here:
        FormPesquisarProduto fpp = new FormPesquisarProduto(this, true);
        fpp.setFv(this);
        fpp.setVisible(true);
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblItens.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Selecione uma linha na tabela");
        }
        else{
            DefaultTableModel tabela = (DefaultTableModel) tblItens.getModel();
            tabela.removeRow(linhaSelecionada);
            calcularValorTotal();
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnConcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirVendaActionPerformed
        // TODO add your handling code here:
        //validar se existe pelo menos 1 item na tabela
        int countTabela = tblItens.getRowCount();
        if(countTabela == 0){
            JOptionPane.showMessageDialog(this, "Adicione pelo menos 1 produto na tabela");
        }
        else{
            //Cria o cliente
            Cliente c = new Cliente();
            c.setId(Integer.parseInt(txtIdCliente.getText()));
            
            //Cria a lista de Itens e pega os itens na tabela
            List<Itens> itens = new ArrayList();
            for(int x = 0; x < countTabela; x++) {
                Itens i = new Itens();
                //pega o produto(item) e a quantidade
                Produto p = new Produto();
                p.setId(Integer.parseInt(
                    tblItens.getValueAt(x, 0).toString()
                ));
                
                i.setProduto(p);
                i.setQuantidade(Integer.parseInt(
                    tblItens.getValueAt(x, 3).toString()
                ));
                
                //add o i na lista
                itens.add(i);
            }
            
            //Por fim, crie a venda
            Venda v = new Venda();
            v.setDatavenda(txtDataVenda.getText());
            v.setValortotal(Double.parseDouble(txtValorTotal.getText()));
            v.setFormapagamento(cmbFormaPagamento.getSelectedItem().toString());
            
            v.setCliente(c);
            v.setItens(itens);
            
            //Salvar a venda
            VendaDAO vendaDAO = new VendaDAO();
            try {
                vendaDAO.inserir(v);
                JOptionPane.showMessageDialog(this, "Venda efetuada com sucesso!");
                this.dispose(); //fecha o form de venda
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnConcluirVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnConcluirVenda;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JComboBox<String> cmbFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtDataVenda;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
